// <auto-generated />
using ClinicManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagement.Migrations
{
    [DbContext(typeof(ClinicManagementDbContext))]
    partial class ClinicManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicManagement.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            contact = "074 226 1505",
                            email = "hlongwaniab@gmail.com",
                            first_name = "Masingita",
                            last_name = "Hlongwani",
                            speciality = "Children"
                        },
                        new
                        {
                            Id = 2,
                            contact = "074 226 1505",
                            email = "abelmasingita9@gmail.com",
                            first_name = "Abel",
                            last_name = "Hlongwani",
                            speciality = "Teeth"
                        },
                        new
                        {
                            Id = 3,
                            contact = "074 226 1505",
                            email = "abelmasingita9@gmail.com",
                            first_name = "Moses",
                            last_name = "Hlongwani",
                            speciality = "Eyes"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            contact = "074 226 1505",
                            dateOfBirth = "20010607",
                            email = "hlongwaniabb@gmail.com",
                            first_name = "Masingitas",
                            gender = "Male",
                            last_name = "Hlongwanii"
                        },
                        new
                        {
                            Id = 2,
                            contact = "074 226 1505",
                            dateOfBirth = "20010607",
                            email = "abelmasingita9@gmail.com",
                            first_name = "Abel",
                            gender = "Male",
                            last_name = "Hlongwani"
                        },
                        new
                        {
                            Id = 3,
                            contact = "074 226 1505",
                            dateOfBirth = "20010607",
                            email = "abelmasingita9@gmail.com",
                            first_name = "Moses",
                            gender = "Male",
                            last_name = "Hlongwani"
                        });
                });

            modelBuilder.Entity("ClinicManagement.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            contact = "074 226 1505",
                            email = "hlongwaniab@gmail.com",
                            first_name = "Masingitaaa",
                            last_name = "Hlongwani",
                            position = "Nurse"
                        },
                        new
                        {
                            Id = 2,
                            contact = "074 226 1505",
                            email = "abelmasingita9@gmail.com",
                            first_name = "Abelll",
                            last_name = "Hlongwani",
                            position = "Nurse"
                        },
                        new
                        {
                            Id = 3,
                            contact = "074 226 1505",
                            email = "abelmasingita9@gmail.com",
                            first_name = "Mosesss",
                            last_name = "Hlongwani",
                            position = "Nurse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
